SELECT * 
FROM EMPLOYEEDEMOGRAPHICS

SELECT * 
FROM EMPLOYEEDEMOGRAPHICS 
WHERE FIRSTNAME = 'JIM'

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME <> 'JIM'

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE > 30

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE >= 30 AND GENDER = 'MALE'

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE >= 30 OR GENDER = 'MALE'

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE LASTNAME LIKE 'C%'

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE LASTNAME LIKE '%Y'

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
WHERE LASTNAME LIKE '_U%'

SELECT * 
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME IS NOT NULL

SELECT * 
FROM EMPLOYEEDEMOGRAPHICS
WHERE FIRSTNAME IN ('JIM','LEO','LISA')