SELECT GENDER, AGE, COUNT(GENDER) AS COUNTGEN
FROM EMPLOYEEDEMOGRAPHICS
GROUP BY GENDER, AGE

SELECT GENDER, AGE, COUNT(GENDER) AS COUNTGEN
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE >= 30
GROUP BY GENDER, AGE
ORDER BY COUNTGEN

SELECT GENDER, AGE, COUNT(GENDER) AS COUNTGEN
FROM EMPLOYEEDEMOGRAPHICS
WHERE AGE >= 30
GROUP BY GENDER, AGE
ORDER BY AGE

SELECT *
FROM EMPLOYEEDEMOGRAPHICS
ORDER BY AGE DESC, GENDER