SELECT * 
FROM EMPLOYEESALARY
FULL OUTER JOIN Salary
	ON EMPLOYEESALARY.EMPLOYEEID = SALARY.EmployeeID

SELECT * 
FROM EMPLOYEESALARY
UNION ALL
SELECT *
FROM Salary

SELECT * 
FROM EMPLOYEESALARY
UNION 
SELECT *
FROM Salary

SELECT * 
FROM EMPLOYEESALARY
UNION ALL
SELECT *
FROM Salary
ORDER BY EMPLOYEEID DESC