SELECT *
FROM EmployeeDemo

SELECT * 
FROM Salary

-- AFTER USING GROUP BY WE CAN NOT USE WHERE STATEMENT AGAIN THATS WHY HAVING STATEMENT IS INTRODUCED
-- WE CAN USE HAVING BELOW GROUP BY STATEMENT ONLY ELSE IT WILL SHOW AN ERROR 

SELECT JOBTITLE, COUNT(JOBTITLE) AS Employee, AVG(SALARY) AS Average_salary
FROM EmployeeDemo
JOIN Salary
	ON EmployeeDemo.EmployeeID = Salary.EMPLOYEEID
GROUP BY JOBTITLE
HAVING AVG(SALARY) > 44500