SELECT DEMO.FirstName, DEMO.LastName, DEMO.Gender, SAL.SALARY, 
COUNT(GENDER) OVER(PARTITION BY GENDER) AS TotalGender
FROM EmployeeDemo AS DEMO
JOIN Salary AS SAL
	ON DEMO.EmployeeID=SAL.EMPLOYEEID

SELECT DEMO.Gender,COUNT(GENDER)
FROM EmployeeDemo AS DEMO
JOIN Salary AS SAL
	ON DEMO.EmployeeID=SAL.EMPLOYEEID
GROUP BY DEMO.Gender