-- TEMP TABLE
-- WE CAN DO MORE TEMP TABLE WHICH WE CAN NOT DO WITH OUR CTE

DROP TABLE IF EXISTS #TEMP_EMPLOYEE

CREATE TABLE #TEMP_EMPLOYEE1(
	EMPLOYEEID int,
	JOBTITLE varchar(20),
	SALARY int)

SELECT *
FROM #TEMP_EMPLOYEE1

INSERT INTO #TEMP_EMPLOYEE1
SELECT *
FROM [SQL tutorial]..Salary

CREATE TABLE #TEMP_EMPLOYEE2(
	JOBTITLE VARCHAR(50),
	EMPLOYEESPERJOB INT,
	AVGAGE INT,
	AVGSALARY INT)

INSERT INTO #TEMP_EMPLOYEE2
SELECT SAL.JOBTITLE, COUNT(JOBTITLE), AVG(DEMO.Age), AVG(SAL.SALARY)
FROM EmployeeDemo AS DEMO
JOIN Salary AS SAL
	ON DEMO.EmployeeID = SAL.EMPLOYEEID
GROUP BY JOBTITLE

SELECT * FROM #TEMP_EMPLOYEE2